Fix sort order issue for items
inviqa/mx-megamenu pull request #2
Opened 2018-07-09 14:33 UTC by kispali

2018-07-09 14:51 UTC, tkotosz requested changes

2018-07-09 14:51 UTC, tkotosz commented on src/MX/MegaMenu/Model/Menu.php
> +            if ($previous['sort_order'] == $next['sort_order']) {
you can use spaceship operator hre

2018-07-09 14:51 UTC, tkotosz commented on src/MX/MegaMenu/Model/Menu.php
> +        MenuItem $menuItem,
do not use the model class directly, use factory instead

2018-07-09 15:15 UTC, kispali commented
Everything is sorted.

2018-07-12 08:27 UTC, tkotosz approved these changes

2018-07-12 10:44 UTC, merged