Add custom class, remove category line features
inviqa/mx-megamenu pull request #26
Opened 2018-11-08 17:05 UTC by kispali

2018-11-09 08:57 UTC, eddichen approved these changes
Approved FE parts

2018-11-13 11:25 UTC, eddichen approved these changes

2018-11-23 08:14 UTC, tkotosz requested changes

2018-11-23 08:14 UTC, tkotosz commented on src/MX/MegaMenu/Block/Adminhtml/Menu/Edit/Form.php
> +            'MX\MegaMenu\Data\Form\Element\Toggle',
:point_up: import class pls

2018-11-23 08:14 UTC, tkotosz commented on src/MX/MegaMenu/Model/Menu.php
>              if ($item['menu_item_parent_id'] == 0) {
$parentId == 0

2018-11-23 09:33 UTC, kispali commented on src/MX/MegaMenu/Block/Adminhtml/Menu/Edit/Form.php
> +            'MX\MegaMenu\Data\Form\Element\Toggle',
sorted

2018-11-23 09:33 UTC, kispali commented on src/MX/MegaMenu/Model/Menu.php
>              if ($item['menu_item_parent_id'] == 0) {
sorted

2018-11-23 09:37 UTC, tkotosz approved these changes

2018-11-23 10:23 UTC, merged